#!/bin/bash

set -e

export GOROOT=$OPENSHIFT_DATA_DIR/go
export GOPATH=$OPENSHIFT_DATA_DIR/build
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# Install go
# We expect the output of `go version` to be something like
# "go version go1.1.2 darwin/amd64"
GO_VERSION=`go version | awk '{split($0,a," "); print a[3]}'`
if [ "$GO_VERSION" != "go1.1.2" ]; then
  curl https://go.googlecode.com/files/go1.1.2.linux-amd64.tar.gz |
  tar zxf - -C $OPENSHIFT_DATA_DIR
fi

# Copy source code to package folder under $GOPATH
rm -rf $GOPATH 2>/dev/null
SOURCE_CODE_DIR=$GOPATH/src/$OPENSHIFT_APP_NAME
mkdir -p $SOURCE_CODE_DIR
cp -r $OPENSHIFT_REPO_DIR/* $SOURCE_CODE_DIR

# Build binary and move it to package folder
go install $OPENSHIFT_APP_NAME/$OPENSHIFT_APP_NAME
mv $GOPATH/bin/$OPENSHIFT_APP_NAME $GOPATH/src/$OPENSHIFT_APP_NAME
