#!/bin/bash

set -e
export GOROOT=$OPENSHIFT_DATA_DIR/go
export GOPATH=$OPENSHIFT_DATA_DIR/build
# export PATH=$GOPATH/src/$OPENSHIFT_APP_NAME:$GOROOT/bin:$PATH

# Change directory to package, otherwise Go's template library will not find
# the html templates we put under /tmpl
cd $GOPATH/src/$OPENSHIFT_APP_NAME

OPTS="-host=$OPENSHIFT_DIY_IP -port=$OPENSHIFT_DIY_PORT -logtostderr=true -stderrthreshold=INFO"
LOG=$OPENSHIFT_DIY_LOG_DIR/$OPENSHIFT_APP_NAME.log
nohup ./$OPENSHIFT_APP_NAME $OPTS > $LOG 2>&1 &
echo $! > $OPENSHIFT_DATA_DIR/$OPENSHIFT_APP_NAME.pid
